image: node:latest

stages:
  - build

cache:
  - key: key
  - paths:
    - node_modules/

build site:
  stage: build
  only:
    - master
  before_script:
    - cd front-end/
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist