stages:
  - build
  
before-script:
  - cd vue-test/

build site:
  stage: build
  only:
    - master
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist