stages:
  - build

build site:
  image: node:latest
  stage: build
  only:
    - master
  before_script:
    - cd front-end/
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist