cache:
  key: key
  paths:
    - node_modules/

services:
  - redis:latest

Host: redis

build site:
  image: node:latest
  stage: build
  before_script:
    - cd front-end/
  script:
    - npm install --progress=false --save-dev @babel/plugin-syntax-object-rest-spread
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

pytests:
  image: python:3.7
  stage: test
  before_script:
    - apt-get update -qq
    - pip3 install -r requirements.txt
    - cd back-end/
  script:
    - py.test .
  artifacts:
    expire_in: 1 week