cache:
  key: key
  paths:
    - node_modules/

build site:
  image: node:latest
  stage: build
  before_script:
    - cd front-end/
  script:
    - npm install --progress=false --save-dev @babel/plugin-syntax-object-rest-spread
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

pages:
  image: node:latest
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv public public-vue
    - mv dist public
  artifacts:
    paths:
      - public 
  only:
    - master